In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [6]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.arange(20,10)  #1st arg < 2nd arg 

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.zeros(5) #parameter tunning 

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros(5, dtype=int) #hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [20]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((10,10),dtype = int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(2)

array([1., 1.])

In [24]:
np.ones(2, dtype=int)

array([1, 1])

In [26]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [28]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
rand(3,2)

NameError: name 'rand' is not defined

In [31]:
random.rand(3,2)

NameError: name 'random' is not defined

In [44]:
np.random.rand(3,2)

array([[0.22107795, 0.63305594],
       [0.62012531, 0.45449202],
       [0.83568168, 0.12455735]])

In [50]:
np.random.rand(3)

array([0.15168326, 0.68293041, 0.0782184 ])

In [53]:
np.random.randint(4,6)

4

In [60]:
np.random.randint(0,10)

4

In [71]:
np.random.randint(0,10,4)

array([0, 2, 5, 7])

In [72]:
np.random.randint(0,10,5)

array([0, 3, 0, 5, 5])

In [73]:
n = np.random.randint(10,40,(8,10))

In [74]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [78]:
n[5]

array([21, 18, 26, 30, 20, 29, 35, 26, 32, 39])

In [79]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [80]:
n[0:6]

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39]])

In [81]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [82]:
n[::-1]

array([[36, 35, 21, 19, 36, 21, 34, 37, 39, 14],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [37, 24, 34, 38, 15, 18, 36, 24, 18, 30]])

In [83]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [85]:
n[::2]

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31]])

In [86]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [87]:
n[0]

array([37, 24, 34, 38, 15, 18, 36, 24, 18, 30])

In [88]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [ ]:
n[0:5]

In [89]:
n[0,5]

18

In [90]:
n

array([[37, 24, 34, 38, 15, 18, 36, 24, 18, 30],
       [20, 16, 30, 24, 10, 19, 33, 35, 11, 20],
       [28, 35, 26, 14, 16, 36, 13, 19, 32, 33],
       [36, 25, 17, 13, 39, 11, 10, 28, 27, 24],
       [28, 31, 22, 15, 11, 12, 11, 13, 30, 31],
       [21, 18, 26, 30, 20, 29, 35, 26, 32, 39],
       [29, 27, 20, 12, 18, 12, 21, 34, 18, 31],
       [36, 35, 21, 19, 36, 21, 34, 37, 39, 14]])

In [91]:
n[5,-3]

26

In [93]:
import numpy as np

x = np.int32(10)
print(x)        # Output: 10
#print(type(x)) 

10


In [100]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [95]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)